// Code generated by mockery v1.0.0. DO NOT EDIT.

package mockkustomize

import mock "github.com/stretchr/testify/mock"

// Kustomizer is an autogenerated mock type for the Kustomizer type
type Kustomizer struct {
	mock.Mock
}

// ApplyLabels provides a mock function with given fields: resourceDefinition, labels
func (_m *Kustomizer) ApplyLabels(resourceDefinition string, labels map[string]string) ([]byte, error) {
	ret := _m.Called(resourceDefinition, labels)

	var r0 []byte
	if rf, ok := ret.Get(0).(func(string, map[string]string) []byte); ok {
		r0 = rf(resourceDefinition, labels)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, map[string]string) error); ok {
		r1 = rf(resourceDefinition, labels)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
