// Code generated by mockery v1.0.0. DO NOT EDIT.

package mockregistry

import image "github.com/pivotal/image-relocation/pkg/image"
import mock "github.com/stretchr/testify/mock"

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// Relocate provides a mock function with given fields: fromRef, toRef
func (_m *Client) Relocate(fromRef string, toRef string) (image.Name, error) {
	ret := _m.Called(fromRef, toRef)

	var r0 image.Name
	if rf, ok := ret.Get(0).(func(string, string) image.Name); ok {
		r0 = rf(fromRef, toRef)
	} else {
		r0 = ret.Get(0).(image.Name)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(fromRef, toRef)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
